### ISSUE TITLE
‘bgzf_thread_count’ is not a member of ‘seqan3::contrib’

### ISSUE THREAD

**Issue by t-neumann** [sarahet/RLM#2]
Hi,

when compiling RLM I get the following error:

```
(base) root@c7e1a36b5d5f:/build# make
Scanning dependencies of target RLM
[  0%] Building CXX object src/CMakeFiles/RLM.dir/RLM.cpp.o
/RLM/src/RLM.cpp: In function ‘int real_main(cmd_arguments&)’:
/RLM/src/RLM.cpp:147:22: error: ‘bgzf_thread_count’ is not a member of ‘seqan3::contrib’
     seqan3::contrib::bgzf_thread_count = 1;
                      ^~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/RLM.dir/build.make:63: src/CMakeFiles/RLM.dir/RLM.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/RLM.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

Cmake and GCC versions are all fine from what I can see - any clue whats going on?

```
(base) root@c7e1a36b5d5f:/build# cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(base) root@c7e1a36b5d5f:/build# gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by sarahet** [comment]
Hi - I unfortunately can't reproduce this error with gcc 8.3.0 or 8.4.0. Did you check out the submodules, i.e. cloned with ```--recurse-submodules``` or ran ```git submodule update --init --recursive```?

**Comment by SGSSGene** [comment]
Hey, the reason very likely is that zlib is not installed on your system. You have two options:
1. install zlib or
2. remove this single line, but files ending in .gz file won't be readable/writable. (not sure about bam files)

**Comment by sarahet** [comment]
Thanks @SGSSGene for helping out - also my mistake for not adding zlib to the requirements, I will update the README (I think it should be necessary for bam support).

**Comment by sarahet** [comment]
@t-neumann Could you check whether installing zlib fixes the problem for you?

**Comment by t-neumann** [comment]
Yes I thought I had zlib installed but apparently you need to install `zlib1g-dev` and not the plain `zlib1g`. Not it works, thanks.

**Comment by sarahet** [comment]
Great!
