### ISSUE TITLE
CHH and CHG Methylation Rate

### ISSUE THREAD

**Issue by sal123butrus** [sarahet/RLM#8]
Hello! Thank you for developing this great tool. I was wondering if there is an option to output information about CHH and CHG methylation. This would be used to assess the efficiency of bisulfite conversion in each sample.

Thanks,
Salwan

**Comment by sarahet** [comment]
Hi Salwan,

Sorry for the late reply! This is unfortunately not planned as we would expect users to generally also run a standard methylation caller for their analysis (given that RLM only outputs drastically filtered results where only reads covering at least 3 CpG are considered). These tools should then also give you an estimate of CHH and CHG methylation. Given the filtering within RLM, the CHH/CHG rate would also probably be falsified and could not provide you with a solid estimate of the bisulfites conversion efficiency.

Best,
Sara

**Comment by sal123butrus** [comment]
Makes sense, thanks!
